__default__:
  nodes: 1
  tasks: 1
  cpus-per-task: 1
  job-name: "{rule}"
  partition: exacloud
  time: 01:00:00
  mem: 8G
  error: "jobs/{rule}/%j.err"
  error: "jobs/{rule}/%j.out"
bowtie2:
  cpus-per-task: 4
